print("enter five mark")
m1=int(input("enter m1\n"))
m2=int(input("enter m2\n"))
m3=int(input("enter m3\n"))
m4=int(input("enter m4\n"))
m5=int(input("enter m5\n"))
total=m1+m2+m3+m4+m5
avg=total/5
print("mark1",m1)
print("mark2",m2)
print("mark3",m3)
print("mark4",m4)
print("mark5",m5)
print("total mark=",total)
print("avg mark=",avg)